patch:
  summary: Configure Account
  description: Set the client-configurable portions of an Account.
  operationId: configureAccount
  tags:
    - Account
  parameters:
    - $ref: ../../shared/parameters/AccountID.yaml
    - $ref: ../../shared/parameters/AcceptDatetimeFormat.yaml
  requestBody:
    description: Representation of the Account configuration to set
    content:
      application/json:
        schema:
          type: object
          properties:
            alias:
              description: Client-defined alias (name) for the Account
              type: string
            marginRate:
              description: Margin rate.
              type: number
              format: double
  responses:
    200:
      description: The Account was configured successfully.
      headers:
        RequestID:
          $ref: ../../shared/headers/RequestID.yaml
      content:
        application/json:
          schema:
            type: object
            properties:
              clientConfigureTransaction:
                $ref: ../../transactions/types/client-configure/ClientConfigureTransaction.yaml
              lastTransactionID:
                description: The ID of the last Transaction created for the Account.
                type: integer
    400:
      description: The configuration specification was invalid.
      headers:
        RequestID:
          $ref: ../../shared/headers/RequestID.yaml
      content:
        application/json:
          schema:
            allOf:
              - type: object
                properties:
                  clientConfigureRejectTransaction:
                    $ref: ../../transactions/types/client-configure/ClientConfigureRejectTransaction.yaml
              - $ref: ../../shared/errors/helpers/Error4xxTransaction.yaml
    403:
      description: The configuration operation was forbidden on the Account.
      headers:
        RequestID:
          $ref: ../../shared/headers/RequestID.yaml
      content:
        application/json:
          schema:
            allOf:
              - type: object
                properties:
                  clientConfigureRejectTransaction:
                    $ref: ../../transactions/types/client-configure/ClientConfigureRejectTransaction.yaml
              - $ref: ../../shared/errors/helpers/Error4xxTransaction.yaml
    401:
      $ref: ../../shared/errors/401.yaml
    404:
      $ref: ../../shared/errors/404.yaml
    405:
      $ref: ../../shared/errors/405.yaml