AccountID:
  name: accountID
  in: path
  required: true
  schema: 
    $ref: ../accounts/types/AccountID.yaml
  description: Account identifier

AcceptDatetimeFormat:
  name: Accept-Datetime-Format
  in: header
  required: false
  schema:
    type: string
    enum:
      - UNIX
      - RFC3339
  description: Format of DateTime fields in the request and response.

InstrumentName:
  name: instrument
  in: path
  required: true
  schema:
    $ref: ../instruments/types/InstrumentName.yaml
  description: Instrument name

OrderSpecifier:
  name: orderSpecifier
  description: The Order Specifier
  in: path
  type: string # TODO regex on integer or string starting with @
  required: true

ClientRequestID:
  name: ClientRequestID
  description: Client specified RequestID to be sent with request.
  in: header
  type: string

TradeSpecifier:
  name: tradeSpecifier
  description: Specifier for the Trade
  in: path
  type: string # TODO regex on integer or string starting with @
  required: true