patch:
  summary: Configure Account
  description: Set the client-configurable portions of an Account.
  tags:
    - Account
  parameters:
    - $ref: ../../shared/parameters.yaml#/AccountID
    - $ref: ../../shared/parameters.yaml#/AcceptDatetimeFormat
    - name: configureAccountBody
      description: Representation of the Account configuration to set
      in: body
      schema:
        type: object
        properties:
          alias:
            type: string
            description: Client-defined alias (name) for the Account
          marginRate:
            type: number
            format: double
            description: Margin rate.
  responses:
    200:
      description: The Account was configured successfully.
      headers:
        RequestID:
          $ref: ../../shared/headers.yaml#RequestID
      content:
        application/json:
          schema:
            type: object
            properties:
              clientConfigureTransaction:
                $ref: ../../transactions/types/client-configure/ClientConfigureTransaction.yaml
              lastTransactionID:
                type: integer
                description: The ID of the last Transaction created for the Account.
    400:
      description: The configuration specification was invalid.
      schema:
        type: object
        allOf:
          - $ref: ../../shared/errors.yaml#/400
          - properties:
            clientConfigureRejectTransaction:
              $ref: ../../transactions/types/client-configure/ClientConfigureRejectTransaction.yaml
            lastTransactionID:
              type: integer
              description: The ID of the last Transaction created for the Account.
    403:
      description: The configuration operation was forbidden on the Account.
      schema:
        type: object
        allOf:
          - $ref: ../../shared/errors.yaml#/403
          - properties:
            clientConfigureRejectTransaction:
              $ref: ../../transactions/types/client-configure/ClientConfigureRejectTransaction.yaml
            lastTransactionID:
              type: integer
              description: The ID of the last Transaction created for the Account.
    401:
      $ref: ../../shared/errors.yaml#/401
    404:
      $ref: ../../shared/errors.yaml#/404
    405:
      $ref: ../../shared/errors.yaml#/405