name: Tag and release definition
on:
  push:
    branches:
      - master
jobs:
  get_current_version:
    name: Get current version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.version }}
    steps:
      - name: Checkout scripts repo
        uses: actions/checkout@v2
        with:
          repository: geriremenyi/github-actions-scripts
          path: scripts

      - name: Checkout current
        uses: actions/checkout@v2

      - name: Get current version
        id: package-version
        run: scripts/src/npm/get_package_variable.sh "version"

  does_tag_exist:
    name: Does tag already exist?
    runs-on: ubuntu-latest
    needs:
      - get_current_version
    outputs:
      exists: ${{ steps.check_tag_exists.outputs.exists }}
    steps:
      - name: Get if tag exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: check_tag_exists
        with: 
          tag: ${{ needs.get_current_tag.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tag_and_release:
    name: Tag commit
    runs-on: ubuntu-latest
    needs:
      - get_current_version
      - does_tag_exist
    if: ${{ needs.does_tag_exist.outputs.exists == 'false' }}
    steps:
      - name: Upload definition files
        uses: actions/upload-artifact@v2
        with:
          name: openapi-definition
          path: src/*.yaml

      - name: Push tag
        uses: mathieudutour/github-tag-action@v5.5
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ needs.get_current_tag.outputs.version }}
          tag_prefix: ""
      
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.get_current_tag.outputs.version }}
          release_name: ${{ needs.get_current_tag.outputs.version }}
          body: ${{ steps.tag_version.outputs.changelog }}