name: Check & Bump Version
on:
  pull_request:
    branches:
      - master
jobs:
  check_src_changes:
    name: Check changes in src folder
    runs-on: ubuntu-latest
    outputs:
      old_hash: ${{ steps.get_stored_hash.outputs.srcHash }}
      new_hash: ${{ steps.calculate_hash.outputs.hash }}
      is_src_changed: ${{ steps.is_src_changed.outputs.changed }}
    steps:
      - name: Checkout current
        uses: actions/checkout@v2
      - name: Get stored hash
        id: get_stored_hash
        run: ./.github/scripts/get_package_variable.sh "srcHash"
      - name: Calculate src folder hash
        id: calculate_hash
        run: ./.github/scripts/calculate_hash.sh "src"
      - name: Check src changes
        id: is_src_changed
        run: |
          is_changed=`[ "${{ steps.get_stored_hash.outputs.srcHash }}" = "${{ steps.calculate_hash.outputs.hash }}" ] && echo false || echo true`
          [ $is_changed = true ] && echo "Version update check and bump is required." || echo "Version updated check and bump is not required."
          echo "::set-output name=changed::is_changed"
  get_current_version:
    name: Get current version
    runs-on: ubuntu-latest
    needs:
      - check_src_changes
    outputs:
      version: ${{ steps.package-version.outputs.version }}
    if: ${{ needs.check_src_changes.outputs.is_src_changed }}
    steps:
      - name: Checkout current
        uses: actions/checkout@v2
      - name: Get current version
        id: package-version
        run: ./.github/scripts/get_package_variable.sh "version"
  get_master_version:
    name: Get master version
    runs-on: ubuntu-latest
    needs:
      - check_src_changes
    outputs:
      version: ${{ steps.package-version.outputs.version }}
    if: ${{ needs.check_src_changes.outputs.is_src_changed }}
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        #with:
          #ref: master
      - name: Get master version
        id: package-version
        run: ./.github/scripts/get_package_variable.sh "version"
  # bump_version_and_hash:
  #     name: Auto bump version and hash if needed
  #     runs-on: ubuntu-latest
  #     env:
  #       GIT_PUSH_AUTHOR_EMAIL: ${{ secrets.BOT_USER_EMAIL }}
  #       GIT_PUSH_AUTHOR_NAME: ${{ secrets.BOT_USER_NAME }}
  #     needs:
  #       - check_src_changes
  #       - get_current_version
  #       - get_master_version
  #     if: ${{ always() }} && ${{ needs.check_src_changes.outputs.is_src_changed }}
  #     steps:
  #       - name: Checkout current
  #         uses: actions/checkout@v2
  #       - name: Update hash
  #         run: ./.github/scripts/set_package_variable.sh "srcHash" ${{ needs.check_src_changes.new_hash }}
  #       - name: Bump patch version
  #         run: ./.github/scripts/bump_version.sh "patch"
  #       - name: Push updated version
  #         run: ./.github/scripts/git_push.sh "Auto patch version bump"