name: Check & Bump Version
on:
  pull_request:
    branches:
      - master
jobs:
  current_version:
    name: Checkout latest commit and get version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.current-version }}
    steps:
      - name: Checkout current
        uses: actions/checkout@v2   
      - name: Get current version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master    
  master_version:
    name: Checkout master branch and get version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.current-version }}
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Get master version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
  check_version:
      name: Bump version if needed
      runs-on: ubuntu-latest
      needs:
        - current_version
        - master_version
      if: needs.current_version.outputs.version != needs.master_version.outputs.version
      steps:
        - name: Checkout current
          uses: actions/checkout@v2
        - name: Check version
          run: |
            echo "Current master version is ${{ needs.master_version.outputs.version }} while the current PR version is ${{ needs.current_version.outputs.version }}"
            [ ${{ needs.master_version.outputs.version }} < ${{ needs.current_version.outputs.version }} ] && exit 1 || exit 0
  bump_version:
      name: Bump version if needed
      runs-on: ubuntu-latest
      needs:
        - current_version
        - master_version
      if: needs.current_version.outputs.version == needs.master_version.outputs.version
      steps:
        - name: Checkout current
          uses: actions/checkout@v2
        - name: Bump patch version
          run: ./scripts/bump_version.sh "patch"
        - name: Push updated version
          uses: ./scripts/git_push.sh "Patch version bump" "${{ secrets.BOT_USER_EMAIL }}" "${{ secrets.BOT_USER_NAME }}"
        


