name: Check & Bump Version
on:
  pull_request:
    branches:
      - master
jobs:
  check_src_changes:
    name: Check changes in src folder
    runs-on: ubuntu-latest
    outputs:
      is_src_changed: ${{ steps.is_src_changed.outputs.changed }}
    steps:
      - name: Checkout current
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Calculate src folder hash
        id: calculate_hash
        run: ./scripts/calculate_hash.sh "src"
      - name: Get stored hash
        id: get_stored_hash
        run: ./scripts/get_package_variable.sh "hash"
      - name: Calculate if update needed
        id: is_src_changed
        run: |
          is_changed=$([ ${{ steps.calculate_hash.outputs.hash }} = ${{ steps.get_stored_hash.outputs.hash }} ] && echo true || echo false)
          [ "$is_changed" = true ] && echo "Version update check and bump is required." || echo "Version updated check and bump is not required."
          echo "::set-output name=changed::is_changed"
  current_version:
    name: Collect current version
    runs-on: ubuntu-latest
    needs:
      - check_src_changes
    outputs:
      version: ${{ steps.package-version.outputs.version }}
    if: ${{ needs.check_src_changes.outputs.is_src_changed }}
    steps:
      - name: Checkout current
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Get current version
        id: package-version
        run: ./scripts/get_package_variable.sh "version"
  master_version:
    name: Collect master version
    runs-on: ubuntu-latest
    needs:
      - check_src_changes
    outputs:
      version: ${{ steps.package-version.outputs.version }}
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        #with:
          #ref: master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Get master version
        id: package-version
        run: ./scripts/get_package_variable.sh "version"
  bump_version:
      name: Auto bump version if needed
      runs-on: ubuntu-latest
      env:
        GIT_PUSH_AUTHOR_EMAIL: ${{ secrets.BOT_USER_EMAIL }}
        GIT_PUSH_AUTHOR_NAME: ${{ secrets.BOT_USER_NAME }}
        GIT_PUSH_TEST: "This is a test message"
      needs:
        - current_version
        - master_version
      if: needs.current_version.outputs.version == needs.master_version.outputs.version
      steps:
        - name: Checkout current
          uses: actions/checkout@v2
        - name: Bump patch version
          run: ./scripts/bump_version.sh "patch"
        - name: Push updated version
          run: ./scripts/git_push.sh "Auto patch version bump"